; /installer_config.iss
; Inno Setup Configuration Script for ControlToKey Windows Deployment

[Setup]
AppId={{C6D2B1E4-F693-4B7B-A6A4-325A384F9321}
AppName=ControlToKey
AppVersion=1.0
AppPublisher=VirusTC
AppPublisherURL=https://github.com
DefaultDirName={autopf}\ControlToKey
DefaultGroupName=ControlToKey
AllowNoIcons=yes
LicenseFile=LICENSE
OutputDir=.
OutputBaseFilename=ControlToKey_Setup_x64
Compression=lzma
SolidCompression=yes
WizardStyle=modern
; Forces the installer to request administrative privileges for secure directory writing
PrivilegesRequired=admin

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; Grab the standalone executable generated by PyInstaller
Source: "dist\ControlToKey.exe"; DestDir: "{app}"; Flags: ignoreversion
; Create an active profiles path and deploy the initial templates securely
Source: "src\windows\profiles\*"; DestDir: "{app}\profiles"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{group}\ControlToKey"; Filename: "{app}\ControlToKey.exe"
Name: "{group}\{cm:UninstallProgram,ControlToKey}"; Filename: "{uninstprog}"
Name: "{autodesktop}\ControlToKey"; Filename: "{app}\ControlToKey.exe"; Tasks: desktopicon

[Run]
; Option to launch the program immediately after installation wraps up
Filename: "{app}\ControlToKey.exe"; Description: "{cm:LaunchProgram,ControlToKey}"; Flags: nowait postinstall skipifsilent

[Registry]
; Configure the executable to automatically launch with Admin Privileges (bypasses UIPI injection drops)
Root: HKLM; Subkey: "SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers"; ValueType: string; ValueName: "{app}\ControlToKey.exe"; ValueData: "~ RUNASADMIN"; Flags: uninsdeletevalue
